module.exports = {
  skills: [
    { id: 'skill_js', name: 'JavaScript' },
    { id: 'skill_python', name: 'Python' },
    { id: 'skill_sql', name: 'SQL' },
    { id: 'skill_react', name: 'React' },
    { id: 'skill_node', name: 'Node.js' },
    { id: 'skill_docker', name: 'Docker' },
    { id: 'skill_k8s', name: 'Kubernetes' },
    { id: 'skill_ml', name: 'Machine Learning' },
    { id: 'skill_stats', name: 'Statistics' },
    { id: 'skill_data_analysis', name: 'Data Analysis' },
    { id: 'skill_cloud', name: 'Cloud Architecture' },
    { id: 'skill_system_design', name: 'System Design' },
    { id: 'skill_leadership', name: 'Leadership' },
    { id: 'skill_pm', name: 'Project Management' },
    { id: 'skill_uiux', name: 'UI/UX Design' },
    { id: 'skill_communication', name: 'Communication' },
    { id: 'skill_graphdb', name: 'Graph Databases' },
    { id: 'skill_devops', name: 'DevOps Pipelines' },
  ],

  // [prerequisiteSkillId, skillId] — prerequisite must be learned first
  skillPrereqs: [
    ['skill_js', 'skill_react'],
    ['skill_js', 'skill_node'],
    ['skill_python', 'skill_ml'],
    ['skill_stats', 'skill_ml'],
    ['skill_python', 'skill_data_analysis'],
    ['skill_sql', 'skill_data_analysis'],
    ['skill_docker', 'skill_k8s'],
    ['skill_node', 'skill_system_design'],
    ['skill_communication', 'skill_leadership'],
    ['skill_pm', 'skill_leadership'],
  ],

  courses: [
    { id: 'course_js101', name: 'JavaScript Fundamentals' },
    { id: 'course_react201', name: 'React in Depth' },
    { id: 'course_node101', name: 'Node.js for Backend Developers' },
    { id: 'course_py101', name: 'Python for Data Science' },
    { id: 'course_sql101', name: 'SQL Mastery' },
    { id: 'course_docker101', name: 'Docker & Containers' },
    { id: 'course_k8s201', name: 'Kubernetes Essentials' },
    { id: 'course_ml201', name: 'Intro to Machine Learning' },
    { id: 'course_stats101', name: 'Statistics for Data Science' },
    { id: 'course_cloud201', name: 'Cloud Architecture on AWS' },
    { id: 'course_sysdesign301', name: 'System Design Interview Prep' },
    { id: 'course_leadership101', name: 'Leadership Foundations' },
    { id: 'course_pm101', name: 'Project Management Certification' },
    { id: 'course_uiux101', name: 'UI/UX Design Basics' },
    { id: 'course_graphdb101', name: 'Graph Databases 101' },
    { id: 'course_devops201', name: 'DevOps Pipelines' },
    { id: 'course_comm101', name: 'Effective Communication' },
  ],

  // [courseId, skillId]
  courseTeaches: [
    ['course_js101', 'skill_js'],
    ['course_react201', 'skill_react'],
    ['course_node101', 'skill_node'],
    ['course_py101', 'skill_python'],
    ['course_sql101', 'skill_sql'],
    ['course_docker101', 'skill_docker'],
    ['course_k8s201', 'skill_k8s'],
    ['course_ml201', 'skill_ml'],
    ['course_stats101', 'skill_stats'],
    ['course_cloud201', 'skill_cloud'],
    ['course_sysdesign301', 'skill_system_design'],
    ['course_leadership101', 'skill_leadership'],
    ['course_pm101', 'skill_pm'],
    ['course_uiux101', 'skill_uiux'],
    ['course_graphdb101', 'skill_graphdb'],
    ['course_devops201', 'skill_devops'],
    ['course_comm101', 'skill_communication'],
  ],

  jobs: [
    { id: 'job_junior_dev', name: 'Junior Developer', level: 1 },
    { id: 'job_frontend_dev', name: 'Frontend Developer', level: 2 },
    { id: 'job_backend_dev', name: 'Backend Developer', level: 2 },
    { id: 'job_data_analyst', name: 'Data Analyst', level: 2 },
    { id: 'job_fullstack_dev', name: 'Full Stack Developer', level: 3 },
    { id: 'job_devops_eng', name: 'DevOps Engineer', level: 3 },
    { id: 'job_data_scientist', name: 'Data Scientist', level: 3 },
    { id: 'job_ml_eng', name: 'Machine Learning Engineer', level: 4 },
    { id: 'job_solutions_architect', name: 'Solutions Architect', level: 4 },
    { id: 'job_eng_manager', name: 'Engineering Manager', level: 4 },
    { id: 'job_cto', name: 'CTO', level: 5 },
  ],

  // [jobId, skillId, importance]
  jobRequires: [
    ['job_junior_dev', 'skill_js', 'core'],
    ['job_junior_dev', 'skill_sql', 'core'],
    ['job_frontend_dev', 'skill_js', 'core'],
    ['job_frontend_dev', 'skill_react', 'core'],
    ['job_frontend_dev', 'skill_uiux', 'nice-to-have'],
    ['job_backend_dev', 'skill_node', 'core'],
    ['job_backend_dev', 'skill_sql', 'core'],
    ['job_backend_dev', 'skill_system_design', 'nice-to-have'],
    ['job_fullstack_dev', 'skill_js', 'core'],
    ['job_fullstack_dev', 'skill_react', 'core'],
    ['job_fullstack_dev', 'skill_node', 'core'],
    ['job_fullstack_dev', 'skill_sql', 'core'],
    ['job_devops_eng', 'skill_docker', 'core'],
    ['job_devops_eng', 'skill_k8s', 'core'],
    ['job_devops_eng', 'skill_cloud', 'core'],
    ['job_devops_eng', 'skill_devops', 'core'],
    ['job_data_analyst', 'skill_sql', 'core'],
    ['job_data_analyst', 'skill_data_analysis', 'core'],
    ['job_data_analyst', 'skill_stats', 'nice-to-have'],
    ['job_data_scientist', 'skill_python', 'core'],
    ['job_data_scientist', 'skill_stats', 'core'],
    ['job_data_scientist', 'skill_ml', 'core'],
    ['job_data_scientist', 'skill_data_analysis', 'core'],
    ['job_ml_eng', 'skill_ml', 'core'],
    ['job_ml_eng', 'skill_python', 'core'],
    ['job_ml_eng', 'skill_cloud', 'nice-to-have'],
    ['job_ml_eng', 'skill_system_design', 'nice-to-have'],
    ['job_solutions_architect', 'skill_cloud', 'core'],
    ['job_solutions_architect', 'skill_system_design', 'core'],
    ['job_solutions_architect', 'skill_communication', 'core'],
    ['job_eng_manager', 'skill_leadership', 'core'],
    ['job_eng_manager', 'skill_pm', 'core'],
    ['job_eng_manager', 'skill_communication', 'core'],
    ['job_eng_manager', 'skill_system_design', 'nice-to-have'],
    ['job_cto', 'skill_leadership', 'core'],
    ['job_cto', 'skill_cloud', 'core'],
    ['job_cto', 'skill_system_design', 'core'],
    ['job_cto', 'skill_communication', 'core'],
  ],

  // [fromJobId, toJobId] — a realistic next step in a career ladder
  jobProgression: [
    ['job_junior_dev', 'job_frontend_dev'],
    ['job_junior_dev', 'job_backend_dev'],
    ['job_frontend_dev', 'job_fullstack_dev'],
    ['job_backend_dev', 'job_fullstack_dev'],
    ['job_backend_dev', 'job_devops_eng'],
    ['job_fullstack_dev', 'job_solutions_architect'],
    ['job_fullstack_dev', 'job_eng_manager'],
    ['job_devops_eng', 'job_solutions_architect'],
    ['job_data_analyst', 'job_data_scientist'],
    ['job_data_scientist', 'job_ml_eng'],
    ['job_ml_eng', 'job_eng_manager'],
    ['job_solutions_architect', 'job_cto'],
    ['job_eng_manager', 'job_cto'],
  ],

  people: [
    { id: 'person_aisha', name: 'Aisha Khan', currentJob: 'job_junior_dev' },
    { id: 'person_raj', name: 'Raj Patel', currentJob: 'job_frontend_dev' },
    { id: 'person_maria', name: 'Maria Silva', currentJob: 'job_backend_dev' },
    { id: 'person_tom', name: 'Tom Becker', currentJob: 'job_data_analyst' },
    { id: 'person_sam', name: 'Sam Okafor', currentJob: 'job_fullstack_dev' },
    { id: 'person_lena', name: 'Lena Wu', currentJob: 'job_solutions_architect' },
    { id: 'person_diego', name: 'Diego Fernandez', currentJob: 'job_eng_manager' },
  ],

  // [personId, skillId, level]
  personSkills: [
    ['person_aisha', 'skill_js', 'intermediate'],
    ['person_aisha', 'skill_sql', 'beginner'],
    ['person_raj', 'skill_js', 'advanced'],
    ['person_raj', 'skill_react', 'advanced'],
    ['person_raj', 'skill_uiux', 'intermediate'],
    ['person_maria', 'skill_node', 'advanced'],
    ['person_maria', 'skill_sql', 'advanced'],
    ['person_maria', 'skill_docker', 'intermediate'],
    ['person_tom', 'skill_sql', 'advanced'],
    ['person_tom', 'skill_data_analysis', 'advanced'],
    ['person_tom', 'skill_stats', 'intermediate'],
    ['person_sam', 'skill_js', 'advanced'],
    ['person_sam', 'skill_react', 'advanced'],
    ['person_sam', 'skill_node', 'advanced'],
    ['person_sam', 'skill_sql', 'intermediate'],
    ['person_lena', 'skill_cloud', 'advanced'],
    ['person_lena', 'skill_system_design', 'advanced'],
    ['person_lena', 'skill_communication', 'advanced'],
    ['person_diego', 'skill_leadership', 'advanced'],
    ['person_diego', 'skill_pm', 'advanced'],
    ['person_diego', 'skill_communication', 'advanced'],
    ['person_diego', 'skill_system_design', 'intermediate'],
  ],
};
